namespace VPDecoder;

// Generated from libvpx VP9 entropy/scan tables; decoded with length guards at startup.
internal static class Vp9ScanTables
{
    private static readonly short[] DefaultScan32X32 = DecodeInt16Table(
        """
        AAAgAAEAQAAhAAIAYABBACIAgAADAGEAQgCgAIEAIwBiAAQAQwCCAKEAwAAkAGMA4AAFAKIAwQBEAIMAJQBkAOEAwgAAAaMA
        RQCEAAYA4gABASABwwBlAKQAJgACAQcA4wAhAYUAQAFGAMQApQAiAQMB5AAnAEEBZgBgAQgAxQBHAIYAQgEjAQQBYQGAAeUA
        pgBnACgAYgFDASQBhwCBAcYABQFIAAkAoAGnAIIBYwHmAEQBaAAlASkAoQHHAIgABgGDAcABRQFkAQoASQCiAecAqADBASYB
        hAFpAKMBBwEqAMgAZQHCAYkA4AFKAEYB6AALAIUBqQAnAaQBagDDAeEBZgEIAUcByQArAIoAAALiAYYBKAHpAKoApQFLAMQB
        ZwEMAAECCQHjAUgBawDKAAICIAKmAYcBxQGLACwA6gDkASkBaAGrAEwAAwIhAgoBSQHGAQ0ApwHLAGwAIgLlAUACKgHrAIwA
        aQFKAawAIwItAMcBCwFBAuYBTQDMAGoBYAIOACsBQgJtAOwA5wFhAksBjQBDAi4ADwCtAGICawFOAM0AEABuAO0AYwKOAC8A
        rgBPAM4AEQBvAO4AMACPAFAArwBwAM8AMQASAO8AUQBxABMAMgBSAHIAMwBTAHMAgAIEAogBDAGQABQAoAKBAiQCBQKoAYkB
        LAENAbAAkQA0ABUAwAKhAoICRAIlAgYCyAGpAYoBTAEtAQ4B0ACxAJIAVAA1ABYA4ALBAqICgwJkAkUCJgIHAugByQGqAYsB
        bAFNAS4BDwHwANEAsgCTAHQAVQA2ABcA4QLCAqMCZQJGAicC6QHKAasBbQFOAS8B8QDSALMAdQBWADcA4gLDAmYCRwLqAcsB
        bgFPAfIA0wB2AFcA4wJnAusBbwHzAHcAAAOEAggCjAEQAZQAGAAgAwEDpAKFAigCCQKsAY0BMAERAbQAlQA4ABkAQAMhAwID
        xAKlAoYCSAIpAgoCzAGtAY4BUAExARIB1AC1AJYAWAA5ABoAYANBAyIDAwPkAsUCpgKHAmgCSQIqAgsC7AHNAa4BjwFwAVEB
        MgETAfQA1QC2AJcAeABZADoAGwBhA0IDIwPlAsYCpwJpAkoCKwLtAc4BrwFxAVIBMwH1ANYAtwB5AFoAOwBiA0MD5gLHAmoC
        SwLuAc8BcgFTAfYA1wB6AFsAYwPnAmsC7wFzAfcAewCAAwQDiAIMApABFAGYABwAoAOBAyQDBQOoAokCLAINArABkQE0ARUB
        uACZADwAHQDAA6EDggNEAyUDBgPIAqkCigJMAi0CDgLQAbEBkgFUATUBFgHYALkAmgBcAD0AHgDgA8EDogODA2QDRQMmAwcD
        6ALJAqoCiwJsAk0CLgIPAvAB0QGyAZMBdAFVATYBFwH4ANkAugCbAHwAXQA+AB8A4QPCA6MDZQNGAycD6QLKAqsCbQJOAi8C
        8QHSAbMBdQFWATcB+QDaALsAfQBeAD8A4gPDA2YDRwPqAssCbgJPAvIB0wF2AVcB+gDbAH4AXwDjA2cD6wJvAvMBdwH7AH8A
        hAMIA4wCEAKUARgBnACkA4UDKAMJA6wCjQIwAhECtAGVATgBGQG8AJ0AxAOlA4YDSAMpAwoDzAKtAo4CUAIxAhIC1AG1AZYB
        WAE5ARoB3AC9AJ4A5APFA6YDhwNoA0kDKgMLA+wCzQKuAo8CcAJRAjICEwL0AdUBtgGXAXgBWQE6ARsB/ADdAL4AnwDlA8YD
        pwNpA0oDKwPtAs4CrwJxAlICMwL1AdYBtwF5AVoBOwH9AN4AvwDmA8cDagNLA+4CzwJyAlMC9gHXAXoBWwH+AN8A5wNrA+8C
        cwL3AXsB/wCIAwwDkAIUApgBHAGoA4kDLAMNA7ACkQI0AhUCuAGZATwBHQHIA6kDigNMAy0DDgPQArECkgJUAjUCFgLYAbkB
        mgFcAT0BHgHoA8kDqgOLA2wDTQMuAw8D8ALRArICkwJ0AlUCNgIXAvgB2QG6AZsBfAFdAT4BHwHpA8oDqwNtA04DLwPxAtIC
        swJ1AlYCNwL5AdoBuwF9AV4BPwHqA8sDbgNPA/IC0wJ2AlcC+gHbAX4BXwHrA28D8wJ3AvsBfwGMAxADlAIYApwBrAONAzAD
        EQO0ApUCOAIZArwBnQHMA60DjgNQAzEDEgPUArUClgJYAjkCGgLcAb0BngHsA80DrgOPA3ADUQMyAxMD9ALVArYClwJ4AlkC
        OgIbAvwB3QG+AZ8B7QPOA68DcQNSAzMD9QLWArcCeQJaAjsC/QHeAb8B7gPPA3IDUwP2AtcCegJbAv4B3wHvA3MD9wJ7Av8B
        kAMUA5gCHAKwA5EDNAMVA7gCmQI8Ah0C0AOxA5IDVAM1AxYD2AK5ApoCXAI9Ah4C8APRA7IDkwN0A1UDNgMXA/gC2QK6ApsC
        fAJdAj4CHwLxA9IDswN1A1YDNwP5AtoCuwJ9Al4CPwLyA9MDdgNXA/oC2wJ+Al8C8wN3A/sCfwKUAxgDnAK0A5UDOAMZA7wC
        nQLUA7UDlgNYAzkDGgPcAr0CngL0A9UDtgOXA3gDWQM6AxsD/ALdAr4CnwL1A9YDtwN5A1oDOwP9At4CvwL2A9cDegNbA/4C
        3wL3A3sD/wKYAxwDuAOZAzwDHQPYA7kDmgNcAz0DHgP4A9kDugObA3wDXQM+Ax8D+QPaA7sDfQNeAz8D+gPbA34DXwP7A38D
        nAO8A50D3AO9A54D/APdA74DnwP9A94DvwP+A98D/wM=
        """,
        1024);

    private static readonly short[] DefaultScan32X32Neighbors = DecodeInt16Table(
        """
        AAAAAAAAAAAAAAAAIAAgAAEAIAABAAEAQABAACEAQAACACEAYABgAAIAAgBBAGAAIgBBAIAAgABhAIAAAwAiAEIAYQADAAMA
        IwBCAGIAgQCBAKAAoACgAAQAIwBDAGIAwADAAAQABACCAKEAoQDAACQAQwBjAIIABQAkAEQAYwDBAOAAogDBAOAA4ACDAKIA
        JQBEAGQAgwAFAAUAwgDhAOEAAAEAAQABowDCAEUAZACEAKMABgAlAOIAAQEGAAYAwwDiAAEBIAFlAIQAIAEgASYARQCkAMMA
        hQCkAAIBIQHjAAIBxADjAAcAJgAhAUABRgBlAEABQAEHAAcApQDEACcARgBmAIUAIgFBAQMBIgHkAAMBQQFgAWABYAHFAOQA
        hgClAEcAZgAIACcAQgFhASMBQgEEASMBZwCGAGEBgAGmAMUA5QAEASgARwAIAAgAgAGAAYcApgBiAYEBQwFiAcYA5QAkAUMB
        SABnAAUBJAEJACgAgQGgAacAxgBoAIcA5gAFAWMBggGgAaABJQFEAUQBYwEJAAkAKQBIAIIBoQHHAOYAiACnAKEBwAEGASUB
        ZAGDAUkAaACDAaIB5wAGAQoAKQCoAMcARQFkAaIBwQFpAIgAwAHAASoASQAmAUUByADnAAoACgBlAYQBiQCoAAcBJgGEAaMB
        SgBpAKMBwgHBAeABRgFlAegABwEnAUYBqQDIAAsAKgBqAIkA4AHgAcIB4QFmAYUBCAEnAckA6ACKAKkAhQGkASsASgCkAcMB
        RwFmAQsACwDhAQAC6QAIAcMB4gEoAUcBSwBqAKoAyQDiAQECAAIAAoYBpQFnAYYBpQHEAWsAigAMACsAygDpAMQB4wEJASgB
        SAFnAYsAqgAsAEsA4wECAgECIALqAAkBKQFIAaYBxQEMAAwAhwGmAasAygBMAGsAAgIhAsUB5AEgAiACCgEpAcsA6gBsAIsA
        SQFoASoBSQGMAKsAAwIiAg0ALACnAcYB6wAKASECQALGAeUBLQBMAKwAywBKAWkBQAJAAg0ADQALASoBIgJBAk0AbADMAOsA
        xwHmAUECYAIrAUoBbQCMACMCQgIOAC0ADgAOAI0ArABCAmECSwFqAS4ATQCtAMwADwAPAE4AbQDNAOwAQwJiAm4AjQAPAC4A
        jgCtAC8ATgCuAM0AEAAQAE8AbgDOAO0AEAAvAG8AjgAwAE8AjwCuAFAAbwCvAM4AEQAwABEAEQDPAO4AMQBQAFEAcAASABIA
        EgAxADIAUQBSAHEAEwAyADMAUgBTAHIAYAJgAuQBAwJoAYcB7AALAXAAjwATABMAgAKAAmECgAIEAiMC5QEEAogBpwFpAYgB
        DAErAe0ADAGQAK8AcQCQABQAMwAUABQAoAKgAoECoAJiAoECJAJDAgUCJALmAQUCqAHHAYkBqAFqAYkBLAFLAQ0BLAHuAA0B
        sADPAJEAsAByAJEANABTABUANAAVABUAwALAAqECwAKCAqECYwKCAkQCYwIlAkQCBgIlAucBBgLIAecBqQHIAYoBqQFrAYoB
        TAFrAS0BTAEOAS0B7wAOAdAA7wCxANAAkgCxAHMAkgBUAHMANQBUABYANQAWABYAwQLgAqICwQKDAqICRQJkAiYCRQIHAiYC
        yQHoAaoByQGLAaoBTQFsAS4BTQEPAS4B0QDwALIA0QCTALIAVQB0ADYAVQAXADYAwgLhAqMCwgJGAmUCJwJGAsoB6QGrAcoB
        TgFtAS8BTgHSAPEAswDSAFYAdQA3AFYAwwLiAkcCZgLLAeoBTwFuAdMA8gBXAHYA4ALgAmQCgwLoAQcCbAGLAfAADwF0AJMA
        FwAXAAADAAPhAgADhAKjAmUChAIIAicC6QEIAowBqwFtAYwBEAEvAfEAEAGUALMAdQCUABgANwAYABgAIAMgAwEDIAPiAgED
        pALDAoUCpAJmAoUCKAJHAgkCKALqAQkCrAHLAY0BrAFuAY0BMAFPAREBMAHyABEBtADTAJUAtAB2AJUAOABXABkAOAAZABkA
        QANAAyEDQAMCAyED4wICA8QC4wKlAsQChgKlAmcChgJIAmcCKQJIAgoCKQLrAQoCzAHrAa0BzAGOAa0BbwGOAVABbwExAVAB
        EgExAfMAEgHUAPMAtQDUAJYAtQB3AJYAWAB3ADkAWAAaADkAGgAaAEEDYAMiA0EDAwMiA8UC5AKmAsUChwKmAkkCaAIqAkkC
        CwIqAs0B7AGuAc0BjwGuAVEBcAEyAVEBEwEyAdUA9AC2ANUAlwC2AFkAeAA6AFkAGwA6AEIDYQMjA0IDxgLlAqcCxgJKAmkC
        KwJKAs4B7QGvAc4BUgFxATMBUgHWAPUAtwDWAFoAeQA7AFoAQwNiA8cC5gJLAmoCzwHuAVMBcgHXAPYAWwB6AGADYAPkAgMD
        aAKHAuwBCwJwAY8B9AATAXgAlwAbABsAgAOAA2EDgAMEAyMD5QIEA4gCpwJpAogCDAIrAu0BDAKQAa8BcQGQARQBMwH1ABQB
        mAC3AHkAmAAcADsAHAAcAKADoAOBA6ADYgOBAyQDQwMFAyQD5gIFA6gCxwKJAqgCagKJAiwCSwINAiwC7gENArABzwGRAbAB
        cgGRATQBUwEVATQB9gAVAbgA1wCZALgAegCZADwAWwAdADwAHQAdAMADwAOhA8ADggOhA2MDggNEA2MDJQNEAwYDJQPnAgYD
        yALnAqkCyAKKAqkCawKKAkwCawItAkwCDgItAu8BDgLQAe8BsQHQAZIBsQFzAZIBVAFzATUBVAEWATUB9wAWAdgA9wC5ANgA
        mgC5AHsAmgBcAHsAPQBcAB4APQAeAB4AwQPgA6IDwQODA6IDRQNkAyYDRQMHAyYDyQLoAqoCyQKLAqoCTQJsAi4CTQIPAi4C
        0QHwAbIB0QGTAbIBVQF0ATYBVQEXATYB2QD4ALoA2QCbALoAXQB8AD4AXQAfAD4AwgPhA6MDwgNGA2UDJwNGA8oC6QKrAsoC
        TgJtAi8CTgLSAfEBswHSAVYBdQE3AVYB2gD5ALsA2gBeAH0APwBeAMMD4gNHA2YDywLqAk8CbgLTAfIBVwF2AdsA+gBfAH4A
        ZAODA+gCBwNsAosC8AEPAnQBkwH4ABcBfACbAIQDowNlA4QDCAMnA+kCCAOMAqsCbQKMAhACLwLxARAClAGzAXUBlAEYATcB
        +QAYAZwAuwB9AJwApAPDA4UDpANmA4UDKANHAwkDKAPqAgkDrALLAo0CrAJuAo0CMAJPAhECMALyARECtAHTAZUBtAF2AZUB
        OAFXARkBOAH6ABkBvADbAJ0AvAB+AJ0AxAPjA6UDxAOGA6UDZwOGA0gDZwMpA0gDCgMpA+sCCgPMAusCrQLMAo4CrQJvAo4C
        UAJvAjECUAISAjEC8wESAtQB8wG1AdQBlgG1AXcBlgFYAXcBOQFYARoBOQH7ABoB3AD7AL0A3ACeAL0AfwCeAMUD5AOmA8UD
        hwOmA0kDaAMqA0kDCwMqA80C7AKuAs0CjwKuAlECcAIyAlECEwIyAtUB9AG2AdUBlwG2AVkBeAE6AVkBGwE6Ad0A/AC+AN0A
        nwC+AMYD5QOnA8YDSgNpAysDSgPOAu0CrwLOAlICcQIzAlIC1gH1AbcB1gFaAXkBOwFaAd4A/QC/AN4AxwPmA0sDagPPAu4C
        UwJyAtcB9gFbAXoB3wD+AGgDhwPsAgsDcAKPAvQBEwJ4AZcB/AAbAYgDpwNpA4gDDAMrA+0CDAOQAq8CcQKQAhQCMwL1ARQC
        mAG3AXkBmAEcATsB/QAcAagDxwOJA6gDagOJAywDSwMNAywD7gINA7ACzwKRArACcgKRAjQCUwIVAjQC9gEVArgB1wGZAbgB
        egGZATwBWwEdATwB/gAdAcgD5wOpA8gDigOpA2sDigNMA2sDLQNMAw4DLQPvAg4D0ALvArEC0AKSArECcwKSAlQCcwI1AlQC
        FgI1AvcBFgLYAfcBuQHYAZoBuQF7AZoBXAF7AT0BXAEeAT0B/wAeAckD6AOqA8kDiwOqA00DbAMuA00DDwMuA9EC8AKyAtEC
        kwKyAlUCdAI2AlUCFwI2AtkB+AG6AdkBmwG6AV0BfAE+AV0BHwE+AcoD6QOrA8oDTgNtAy8DTgPSAvECswLSAlYCdQI3AlYC
        2gH5AbsB2gFeAX0BPwFeAcsD6gNPA24D0wLyAlcCdgLbAfoBXwF+AWwDiwPwAg8DdAKTAvgBFwJ8AZsBjAOrA20DjAMQAy8D
        8QIQA5QCswJ1ApQCGAI3AvkBGAKcAbsBfQGcAawDywONA6wDbgONAzADTwMRAzAD8gIRA7QC0wKVArQCdgKVAjgCVwIZAjgC
        +gEZArwB2wGdAbwBfgGdAcwD6wOtA8wDjgOtA28DjgNQA28DMQNQAxIDMQPzAhID1ALzArUC1AKWArUCdwKWAlgCdwI5AlgC
        GgI5AvsBGgLcAfsBvQHcAZ4BvQF/AZ4BzQPsA64DzQOPA64DUQNwAzIDUQMTAzID1QL0ArYC1QKXArYCWQJ4AjoCWQIbAjoC
        3QH8Ab4B3QGfAb4BzgPtA68DzgNSA3EDMwNSA9YC9QK3AtYCWgJ5AjsCWgLeAf0BvwHeAc8D7gNTA3ID1wL2AlsCegLfAf4B
        cAOPA/QCEwN4ApcC/AEbApADrwNxA5ADFAMzA/UCFAOYArcCeQKYAhwCOwL9ARwCsAPPA5EDsANyA5EDNANTAxUDNAP2AhUD
        uALXApkCuAJ6ApkCPAJbAh0CPAL+AR0C0APvA7ED0AOSA7EDcwOSA1QDcwM1A1QDFgM1A/cCFgPYAvcCuQLYApoCuQJ7ApoC
        XAJ7Aj0CXAIeAj0C/wEeAtED8AOyA9EDkwOyA1UDdAM2A1UDFwM2A9kC+AK6AtkCmwK6Al0CfAI+Al0CHwI+AtID8QOzA9ID
        VgN1AzcDVgPaAvkCuwLaAl4CfQI/Al4C0wPyA1cDdgPbAvoCXwJ+AnQDkwP4AhcDfAKbApQDswN1A5QDGAM3A/kCGAOcArsC
        fQKcArQD0wOVA7QDdgOVAzgDVwMZAzgD+gIZA7wC2wKdArwCfgKdAtQD8wO1A9QDlgO1A3cDlgNYA3cDOQNYAxoDOQP7AhoD
        3AL7Ar0C3AKeAr0CfwKeAtUD9AO2A9UDlwO2A1kDeAM6A1kDGwM6A90C/AK+At0CnwK+AtYD9QO3A9YDWgN5AzsDWgPeAv0C
        vwLeAtcD9gNbA3oD3wL+AngDlwP8AhsDmAO3A3kDmAMcAzsD/QIcA7gD1wOZA7gDegOZAzwDWwMdAzwD/gIdA9gD9wO5A9gD
        mgO5A3sDmgNcA3sDPQNcAx4DPQP/Ah4D2QP4A7oD2QObA7oDXQN8Az4DXQMfAz4D2gP5A7sD2gNeA30DPwNeA9sD+gNfA34D
        fAObA5wDuwN9A5wDvAPbA50DvAN+A50D3AP7A70D3AOeA70DfwOeA90D/AO+A90DnwO+A94D/QO/A94D3wP+AwAAAAA=
        """,
        2050);

    public static ReadOnlySpan<short> GetDefaultScan(Vp9TransformSize transformSize)
    {
        return transformSize switch
        {
            Vp9TransformSize.Tx32X32 => DefaultScan32X32,
            _ => throw new NotSupportedException($"VP9 coefficient scan table for {transformSize} is not implemented yet.")
        };
    }

    public static ReadOnlySpan<short> GetDefaultNeighbors(Vp9TransformSize transformSize)
    {
        return transformSize switch
        {
            Vp9TransformSize.Tx32X32 => DefaultScan32X32Neighbors,
            _ => throw new NotSupportedException($"VP9 coefficient neighbor table for {transformSize} is not implemented yet.")
        };
    }

    public static int GetBand(Vp9TransformSize transformSize, int coefficientIndex)
    {
        if (coefficientIndex < 0 || coefficientIndex >= GetMaximumEob(transformSize))
        {
            throw new ArgumentOutOfRangeException(nameof(coefficientIndex), "VP9 coefficient index is outside the transform block.");
        }

        if (transformSize == Vp9TransformSize.Tx4X4)
        {
            return coefficientIndex switch
            {
                0 => 0,
                <= 2 => 1,
                <= 5 => 2,
                <= 9 => 3,
                <= 12 => 4,
                _ => 5
            };
        }

        return coefficientIndex switch
        {
            0 => 0,
            <= 2 => 1,
            <= 5 => 2,
            <= 9 => 3,
            <= 20 => 4,
            _ => 5
        };
    }

    public static int GetMaximumEob(Vp9TransformSize transformSize)
    {
        return transformSize switch
        {
            Vp9TransformSize.Tx4X4 => 16,
            Vp9TransformSize.Tx8X8 => 64,
            Vp9TransformSize.Tx16X16 => 256,
            Vp9TransformSize.Tx32X32 => 1024,
            _ => throw new ArgumentOutOfRangeException(nameof(transformSize))
        };
    }

    public static int GetCoefficientContext(ReadOnlySpan<short> neighbors, ReadOnlySpan<byte> tokenCache, int coefficientIndex)
    {
        var neighborOffset = coefficientIndex * 2;
        return (1 + tokenCache[neighbors[neighborOffset]] + tokenCache[neighbors[neighborOffset + 1]]) >> 1;
    }

    private static short[] DecodeInt16Table(string base64, int expectedLength)
    {
        var bytes = Convert.FromBase64String(base64);
        if (bytes.Length != expectedLength * 2)
        {
            throw new InvalidOperationException("VP9 generated scan table has an unexpected length.");
        }

        var values = new short[expectedLength];
        for (var i = 0; i < values.Length; i++)
        {
            values[i] = BitConverter.ToInt16(bytes, i * 2);
        }

        return values;
    }
}
